/*Setting Library*/
LIBNAME Cluster "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)";
RUN;

/*To Export SAS Data to Excel FIle*/
ODS HTML FILE = "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)\ClusterData.XLS";
PROC PRINT DATA = Cluster.CLUSTER_DATA;
RUN;ODS HTML CLOSE;

PROC SQL;
Select count(*) FROM Cluster.CLUSTER_DATA;
Quit;

/*Checking Outliers*/
ODS HTML FILE = "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)\Outliers.XLS";
PROC MEANS DATA = Cluster.CLUSTER_DATA MIN MAX
MEAN MEDIAN Q1 Q3 STD;RUN;ODS HTML CLOSE;

/*Univariate Test to check outliers exist or not*/
ODS HTML FILE = "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)\UnivariateTest.XLS";
PROC UNIVARIATE DATA = Cluster.CLUSTER_DATA NEXTROBS = 105;
RUN;ODS HTML CLOSE;

/*Outlier Treatment*/
/*Variables:
TOTAL_DAILY_ORDER_NET_AMT_12	80925
AVG_DAILY_ORDER_NET_AMT_12		16600 		11554.29
TOTAL_LINE_ITEM_QTY_12			80
AVG_LINE_ITEM_QTY_12			5
TOTAL_DOLLAR_DISCOUNT_12		536197 		X 307920
AVG_DOLLAR_DISCOUNT_12			21945.75 	X 10656.25
SIZE_NET_SALES 					1.905025
SIZE_QTY 						1.650989 	X1.228643
SIZE_DOLLAR_DISC 				2.585263 	X1.48463
RATIO_DISC_SALES 				6.88889
med_DAILY_ORDER_NET_AMT_12 		22500 		X12961.5
med_LINE_ITEM_QTY_12 			12 			10
med_DOLLAR_DISCOUNT_12 			21945.75	X12999.78
count 							31
sum_value_12 					498465
*/

/*Outliers Treatment*/
DATA Cluster.CLUSTER_DATA;
SET Cluster.CLUSTER_DATA;
IF TOTAL_DAILY_ORDER_NET_AMT_12>80925 THEN TOTAL_DAILY_ORDER_NET_AMT_12=80925;
IF AVG_DAILY_ORDER_NET_AMT_12>16600 THEN AVG_DAILY_ORDER_NET_AMT_12=16600;
IF TOTAL_LINE_ITEM_QTY_12>80 THEN TOTAL_LINE_ITEM_QTY_12=80;
IF AVG_LINE_ITEM_QTY_12>5 THEN AVG_LINE_ITEM_QTY_12=5;
IF TOTAL_DOLLAR_DISCOUNT_12>307920 THEN TOTAL_DOLLAR_DISCOUNT_12=536197;
IF AVG_DOLLAR_DISCOUNT_12>21945.75 THEN AVG_DOLLAR_DISCOUNT_12=21945.75;
IF SIZE_NET_SALES>1.905025 THEN SIZE_NET_SALES=1.905025;
IF SIZE_QTY>1.650989 THEN SIZE_QTY=1.650989;
IF SIZE_DOLLAR_DISC>2.585263 THEN SIZE_DOLLAR_DISC=2.585263;
IF RATIO_DISC_SALES>6.88889 THEN RATIO_DISC_SALES=6.88889;
IF med_DAILY_ORDER_NET_AMT_12>22500 THEN med_DAILY_ORDER_NET_AMT_12=22500;
IF med_LINE_ITEM_QTY_12>6 THEN med_LINE_ITEM_QTY_12=6;
IF med_DOLLAR_DISCOUNT_12>21945.75 THEN med_DOLLAR_DISCOUNT_12=21945.75;
IF count>31 THEN count=31;
IF sum_value_12>498465 THEN sum_value_12=498465;
RUN;


/*Missing Value Checking*/
ODS HTML FILE = "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)\MissingValue.XLS";
PROC MEANS DATA = Cluster.CLUSTER_DATA Nmiss;
RUN;
ODS HTML CLOSE;

/*MISSING VALUES*/
PROC MEANS DATA = D.A MEAN NMISS;RUN;
PROC MEANS DATA = D.A MIN MAX MEAN NMISS;
VAR MEALS;CLASS MEALCAT;RUN;

/*FACTOR ANALYSIS*/
PROC FACTOR: 
NFACT: NO OF FACTORS GENERALLY KEPT SAME AS THE NUMBER OF VARIABLES
METHOD: PRIN (SHORT FORM FOR PRINCIPAL COMPONENT ANALYSIS)
ROTATE : VARIMAX (ROTATION METHOD ENSURING ORTHOGANILITY OF FACTORS)
OUT : OUTPUT FILE WHICH STORE THE FACTOR SCORES;

ODS HTML FILE = "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)\FactorAnalysis.XLS";
PROC FACTOR DATA = Cluster.CLUSTER_DATA NFACT = 18 
METHOD = PRIN ROTATE = VARIMAX OUT = Cluster.FAC;
VAR
med_Actual_price_12
AVG_Actual_price_12
TOTAL_DAILY_ORDER_NET_AMT_12
AVG_DAILY_ORDER_NET_AMT_12
TOTAL_LINE_ITEM_QTY_12
AVG_LINE_ITEM_QTY_12
TOTAL_DOLLAR_DISCOUNT_12
AVG_DOLLAR_DISCOUNT_12
SIZE_NET_SALES
SIZE_QTY
SIZE_DOLLAR_DISC
RATIO_DISC_SALES
med_DAILY_ORDER_NET_AMT_12
med_LINE_ITEM_QTY_12
med_DOLLAR_DISCOUNT_12
MONTH_SINCE_LAST_TRANSACTION
count
sum_value_12
;
RUN; 
QUIT;
ODS HTML CLOSE;

/*To check the correlation between Factors*/
PROC CORR data = Cluster.fac;
var
Factor1	Factor2	Factor3	Factor4	Factor5	Factor6	Factor7	
Factor8	Factor9	Factor10	Factor11	Factor12	
Factor13	Factor14	Factor15	Factor16	Factor17	Factor18
;RUN;

/*STANDARDISATION*/
/*only selected variables from factor analysis*/
/*to be standardised*/
PROC STANDARD DATA = Cluster.CLUSTER_DATA
MEAN = 0 STD = 1 OUT = Cluster.Standard;
VAR
AVG_Actual_price_12
TOTAL_DAILY_ORDER_NET_AMT_12
AVG_DOLLAR_DISCOUNT_12
MONTH_SINCE_LAST_TRANSACTION 
sum_value_12
;
RUN;
quit;

/*CLUSTER FORMATION*/
ODS HTML FILE = "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)\ClusterFormation.XLS";
PROC FASTCLUS DATA = Cluster.Standard MAXC = 50
MAXITER = 150 DELETE = 36 OUT = Cluster.CLOUT; 
VAR
AVG_Actual_price_12
TOTAL_DAILY_ORDER_NET_AMT_12
AVG_DOLLAR_DISCOUNT_12
MONTH_SINCE_LAST_TRANSACTION 
sum_value_12
;
QUIT;
ODS HTML CLOSE;

/*GETTING CLUSTER MEMBERSHIP 
VARIABLE IN THE ORIGINAL FILE*/
/*Merge Cluster Column with Original Data*/
PROC SQL;
CREATE TABLE Cluster.FIN 
AS SELECT X.*,Y.CLUSTER
FROM Cluster.CLUSTER_DATA X,Cluster.CLOUT Y
WHERE X.CUST_ID = Y.CUST_ID;
QUIT;

/*Cluster mean w.r.t each variable*/
ODS HTML FILE = "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)\ClusterMEAN.XLS";
PROC MEANS DATA = Cluster.FIN MEAN;
VAR 
AVG_Actual_price_12
TOTAL_DAILY_ORDER_NET_AMT_12
AVG_DOLLAR_DISCOUNT_12
MONTH_SINCE_LAST_TRANSACTION 
sum_value_12;
CLASS CLUSTER;
RUN;
ods HTML CLOSE;

/*
1. EXCEL FILE SHOWING ALL CHECKS SATISFIED
2. PPT - CLUSTER PROFILE AND STRATEGY FOR 
EACH CLUSTER
*/

ODS HTML FILE = "C:\SAS_101\CASE STUDIES\Customer Profiling(Cluster Analysis)\Temp.XLS";
PROC SQL;
SELECT * FROM Cluster.Fin X WHERE X.Cluster=4;
QUit;
ods HTML CLOSE;
